/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MapRouteImport } from './routes/map'
import { Route as QuizDemoRouteImport } from './routes/quiz-demo'
import { Route as MonumentSlugRouteImport } from './routes/monument.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizDemoRoute = QuizDemoRouteImport.update({
  id: '/quiz-demo',
  path: '/quiz-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const MonumentSlugRoute = MonumentSlugRouteImport.update({
  id: '/monument/$slug',
  path: '/monument/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/quiz-demo': typeof QuizDemoRoute
  '/monument/$slug': typeof MonumentSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/quiz-demo': typeof QuizDemoRoute
  '/monument/$slug': typeof MonumentSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/quiz-demo': typeof QuizDemoRoute
  '/monument/$slug': typeof MonumentSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/map' | '/quiz-demo' | '/monument/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/map' | '/quiz-demo' | '/monument/$slug'
  id: '__root__' | '/' | '/auth' | '/map' | '/quiz-demo' | '/monument/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MapRoute: typeof MapRoute
  QuizDemoRoute: typeof QuizDemoRoute
  MonumentSlugRoute: typeof MonumentSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-demo': {
      id: '/quiz-demo'
      path: '/quiz-demo'
      fullPath: '/quiz-demo'
      preLoaderRoute: typeof QuizDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monument/$slug': {
      id: '/monument/$slug'
      path: '/monument/$slug'
      fullPath: '/monument/$slug'
      preLoaderRoute: typeof MonumentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MapRoute: MapRoute,
  QuizDemoRoute: QuizDemoRoute,
  MonumentSlugRoute: MonumentSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
